# Память и оптимизации для Dev Containers / GitHub Codespaces
org.gradle.jvmargs=-Xmx1536m -XX:+UseG1GC
org.gradle.parallel=false
org.gradle.workers.max=1
fabric.loom.decompile.memory=1280m

# IntelliJ IDEA Configuration Cache
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.160.0+26.2

# Mod Properties
version=1.0.0
group=com.example
